@host = http://localhost:5000
@api = {{host}}/agendas-module
@url = {{api}}/submissions

@email = teo@vincent.com
@password = sicret
@accessToken = {{access_token.response.body.accessToken}}

### Get access token for the user
# @name access_token
POST {{host}}/users-module/account/sign-in
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}

### Add new
# @name new_created
POST {{url}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "ConferenceId": "a73d482c-3acd-4b5d-b0d5-fd3712872b31",
    "Title": "Title of submission ### 7004",
    "Description": "Descripton of submission",
    "Level": "1",
    "Tags": [ "tag_one", "tag_two", "tag_three"],
    "SpeakerIds": [ 
        "5fa6e5ab-c3ae-42c1-b480-2e2117d361c3", 
        "e8e6a7ed-f917-4a1c-89ae-bc21796d3933"
        ]
}

### ID variable
@id = {{new_created.response.body.id}}

### Get
GET {{url}}/{{id}}

### Arleady created location variable
@hostLocation = {{new_created.response.headers.Location}}

### Get arleady created
GET {{hostLocation}}

### Approve submission
PUT {{url}}/{{id}}/approvals

### Reject submission
PUT {{url}}/{{id}}/rejections