@host = http://localhost:5000
@api = {{host}}/agendas-module
@conferenceId = 26914b94-ce02-474d-bb8c-24d5b0470fca
@url = {{api}}/agendas/{{conferenceId}}

@email = teo@vincent.com
@password = sicret
@accessToken = {{access_token.response.body.accessToken}}

### Get access token for the user
# @name access_token
POST {{host}}/users-module/account/sign-in
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}

### Get Agenda Items
GET {{url}}/items
Content-Type: application/json

### Get Agenda Item
GET {{url}}/items/{{conferenceId}}
Content-Type: application/json

@trackId = ca7c14e5-ba10-4dd6-b652-20bf7b700c3a

### Create track
POST {{url}}/tracks
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "Name": "Agenda track 2"
}

### Get Agenda Track
GET {{url}}/tracks/{{trackId}}
Content-Type: application/json

### Create slot
POST {{url}}/slots
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "AgendaTrackId": "{{trackId}}",
    "From": "2021-05-01T11:30:00",
    "To": "2021-05-01T12:30:00",
    "ParticipantsLimit": 85,
    "Type": "regular"
}

### Assign placeholder to slot in track
POST {{url}}/slots/placeholder-assignments
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "AgendaSlotId": "6b1cbdeb-616e-43bc-adad-e6101adaf0ac",
    "AgendaTrackId": "{{trackId}}",
    "Placeholder": "Przerwa kawowa nr. 1"
}

### Assign regular to slot in track
POST {{url}}/slots/regular-assignments
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "AgendaSlotId": "e3b9d51a-d51e-4dbd-a303-9316d4b91ce5",
    "AgendaTrackId": "{{trackId}}",
    "AgendaItemId": "c9c570aa-ac14-441e-a48d-e280714184c1"
}