@host = http://localhost:5000
@api = {{host}}/agendas-module
@conferenceId = 26914b94-ce02-474d-bb8c-24d5b0470fca
@url = {{api}}/agendas/{{conferenceId}}

@email = teo@vincent.com
@password = sicret
@accessToken = {{access_token.response.body.accessToken}}

### Get access token for the user
# @name access_token
POST {{host}}/users-module/account/sign-in
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}

### Get Agenda Items
GET {{url}}/items
Content-Type: application/json

### Get Agenda Item
GET {{url}}/items/{{conferenceId}}
Content-Type: application/json

### Get Agenda Track
GET {{url}}
Content-Type: application/json

### Create track
POST {{url}}/tracks
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "Name": "Agenda track 1"
}
