@eventId = bddebff7-7aab-4d6b-bb1e-be6a591bdbe3

@host = http://localhost:5000
@api = {{host}}/attendances-module
@url = {{api}}/attendances

@email = teo@vincent.com
@password = sicret
@accessToken = {{access_token.response.body.accessToken}}

### Get access token for the user
# @name access_token
POST {{host}}/users-module/account/sign-in
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}

###
GET {{api}}

### Attend an event
POST {{url}}/events/{{eventId}}/attend
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
}