@host = http://localhost:5000
@api = {{host}}/conferences-module
@url = {{api}}/conferences

@email = teo@vincent.com
@password = sicret
@accessToken = {{access_token.response.body.accessToken}}

### Get access token for the user
# @name access_token
POST {{host}}/users-module/account/sign-in
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}

### Get hello Conferences Module API message
GET {{api}}

### Get
GET {{url}}

### Add new
# @name new_created_location
POST {{url}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "HostId": "f5d9488b-1ad9-442c-a7b7-fa974457548b",
    "Name": "Name of conference #1",
    "Description": "Description of conference #1",
    "From": "2021-05-01",
    "To": "2021-05-03",
    "Localization": "Melbourne",
    "ParticipantsLimit": 100,
    "LogoUrl": null
}

### ID variable
@conferenceId = 2de70676-8852-4103-8bf3-4e674d3aea57

### Get
GET {{url}}/{{conferenceId}}

### Update
PUT {{url}}/{{conferenceId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "Name": "Name of conference #1",
    "Description": "Description of conference #1",
    "From": "2021-05-01",
    "To": "2021-05-03",
    "Localization": "Melbourne",
    "ParticipantsLimit": 100,
    "LogoUrl": null
}

### Delete
DELETE {{url}}/{{conferenceId}}
Authorization: Bearer {{accessToken}}

### Arleady created location variable
@hostLocation = {{new_created_location.response.headers.Location}}

### Get arleady created
GET {{hostLocation}}