
@host = http://localhost:5000
@base = conferences-module
@api = {{host}}/{{base}}

### Get hello conferences API message
GET {{api}}

### Get hosts
GET {{api}}/hosts

### Add new host
# @name new_host_created_location
POST {{api}}/hosts
Content-Type: application/json

{
    "Name": "Name of host #1",
    "Description": "Description of host #1"
}

### Temp arleady created host location variable
@hostLocation = {{new_host_created_location.response.headers.Location}}

### Get arleady created host
GET {{hostLocation}}

@hostId = f264d031-d58b-49c2-bc60-8eca58454265

### Get host
GET {{api}}/hosts/{{hostId}}

### Update host
PUT {{api}}/hosts/{{hostId}}
Content-Type: application/json

{
    "Name": "Edited name",
    "Description": "Edited description",
    "Conferences": [ ]
}
