@host = http://localhost:5000
@api = {{host}}/speakers-module
@url = {{api}}/speakers

@email = teo@vincent.com
@password = sicret
@accessToken = {{access_token.response.body.accessToken}}

### Get access token for the user
# @name access_token
POST {{host}}/users-module/account/sign-in
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}


### Get hello Speakers Module API message
GET {{api}}

### Get
GET {{url}}

### Add new
# @name new_created_location
POST {{url}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "FullName": "Teo Vincent",
    "Email": "art@gmail.com",
    "Bio": "A bio desctipiton.",
    "AvatarUrl": ""
}

### ID variable
@speakerId = 5b6dcb39-a99f-432d-b9ab-69aec171e708

### Get
GET {{url}}/{{speakerId}}

### Update
PUT {{url}}/{{speakerId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "FullName": "Edit Full Name",
    "Email": "art2@gmail.com",
    "Bio": "Edited the bio.",
    "AvatarUrl": ""
}

### Delete
DELETE {{url}}/{{speakerId}}
Authorization: Bearer {{accessToken}}

### Arleady created location variable
@speakerLocation = {{new_created_location.response.headers.Location}}

### Get arleady created
GET {{speakerLocation}}