// <auto-generated />
using System;
using Confab.Modules.Agendas.Infrastructure.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Confab.Modules.Agendas.Infrastructure.EF.Migrations
{
    [DbContext(typeof(AgendasDbContext))]
    [Migration("20211028182044_Agendas_Module_Tracks")]
    partial class Agendas_Module_Tracks
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("agendas")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Confab.Modules.Agendas.Domain.Agendas.Entities.AgendaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AgendaItems");
                });

            modelBuilder.Entity("Confab.Modules.Agendas.Domain.Agendas.Entities.AgendaSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("From")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("To")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("TrackId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.ToTable("AgendaSlots");

                    b.HasDiscriminator<string>("Type").HasValue("AgendaSlot");
                });

            modelBuilder.Entity("Confab.Modules.Agendas.Domain.Agendas.Entities.AgendaTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AgendaTracks");
                });

            modelBuilder.Entity("Confab.Modules.Agendas.Domain.CallForPaper.Entities.CallForPapers", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConferenceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("From")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsOpened")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("To")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CallForPapers");
                });

            modelBuilder.Entity("Confab.Modules.Agendas.Domain.Submissions.Entities.Speaker", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgendaItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgendaItemId");

                    b.ToTable("Speakers");
                });

            modelBuilder.Entity("Confab.Modules.Agendas.Domain.Submissions.Entities.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("SpeakerSubmission", b =>
                {
                    b.Property<Guid>("SpeakersId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubmissionsId")
                        .HasColumnType("uuid");

                    b.HasKey("SpeakersId", "SubmissionsId");

                    b.HasIndex("SubmissionsId");

                    b.ToTable("SpeakerSubmission");
                });

            modelBuilder.Entity("Confab.Modules.Agendas.Domain.Agendas.Entities.PlaceholderAgendaSlot", b =>
                {
                    b.HasBaseType("Confab.Modules.Agendas.Domain.Agendas.Entities.AgendaSlot");

                    b.Property<string>("Placeholder")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("placeholder");
                });

            modelBuilder.Entity("Confab.Modules.Agendas.Domain.Agendas.Entities.RegularAgendaSlot", b =>
                {
                    b.HasBaseType("Confab.Modules.Agendas.Domain.Agendas.Entities.AgendaSlot");

                    b.Property<Guid?>("AgendaItemId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ParticipantLimit")
                        .HasColumnType("integer");

                    b.HasIndex("AgendaItemId");

                    b.HasDiscriminator().HasValue("regular");
                });

            modelBuilder.Entity("Confab.Modules.Agendas.Domain.Agendas.Entities.AgendaSlot", b =>
                {
                    b.HasOne("Confab.Modules.Agendas.Domain.Agendas.Entities.AgendaTrack", "Track")
                        .WithMany("Slots")
                        .HasForeignKey("TrackId");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Confab.Modules.Agendas.Domain.Submissions.Entities.Speaker", b =>
                {
                    b.HasOne("Confab.Modules.Agendas.Domain.Agendas.Entities.AgendaItem", null)
                        .WithMany("Speakers")
                        .HasForeignKey("AgendaItemId");
                });

            modelBuilder.Entity("SpeakerSubmission", b =>
                {
                    b.HasOne("Confab.Modules.Agendas.Domain.Submissions.Entities.Speaker", null)
                        .WithMany()
                        .HasForeignKey("SpeakersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Confab.Modules.Agendas.Domain.Submissions.Entities.Submission", null)
                        .WithMany()
                        .HasForeignKey("SubmissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Confab.Modules.Agendas.Domain.Agendas.Entities.RegularAgendaSlot", b =>
                {
                    b.HasOne("Confab.Modules.Agendas.Domain.Agendas.Entities.AgendaItem", "AgendaItem")
                        .WithMany()
                        .HasForeignKey("AgendaItemId");

                    b.Navigation("AgendaItem");
                });

            modelBuilder.Entity("Confab.Modules.Agendas.Domain.Agendas.Entities.AgendaItem", b =>
                {
                    b.Navigation("Speakers");
                });

            modelBuilder.Entity("Confab.Modules.Agendas.Domain.Agendas.Entities.AgendaTrack", b =>
                {
                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
